@startuml
'https://plantuml.com/class-diagram

class Table {
    - data: Map<string, any>
    - headers: string[]
    + set_cell(address: string, data: any): void
    + get_cell(address: string): any
    + get_row(rowNumber: int): Map<string, any>
    + get_column(columnLetter: string): Map<string, any>
    + add_row(rowData: any[]): void
    + add_column(headerName: string, columnData: any[]): void
}

class Worksheet {
    - name: string
    - tables: dict<string, Table>
    + add_table(table_name: string): void
    + get_table(table_name: string): Table
}

class Workbook {
    - name: string
    - worksheets: dict<string, Worksheet>
    + add_worksheet(worksheet_name: string): void
    + remove_worksheet(worksheet_name: string): void
    + get_worksheet(worksheet_name: string): Worksheet
    + call_macro(macro_name: string): void
}

class PDF {
    + name: string
    + total: float
    + date: date (MM-DD-YYYY)
    + invoice_number: int
    + filePath: string
    + extract_text(): string
    + extract_data_by_pattern(pattern: string): any[]
    + perform_OCR(): string
}

class PDFCollection {
    - pdfs: dict<string, PDF>
    + add_pdf(filePath: string): void
    + remove_pdf(filePath: string): void
    + get_pdf(filePath: string): PDF
    + apply_operation_to_all(operation: Function): void
}

Workbook *- "1..*" Worksheet : contains
Worksheet *- "0..*" Table : contains
Worksheet --> PDFCollection : "utilizes"
PDFCollection *- "0..*" PDF : contains

@enduml
