@startuml

actor "Amex Workbook\n(Mar '24)" as Amex
actor Ana
actor Brandon
actor "Automation.py" as Amex_Automation
actor "Invoice Folder" as Invoice_Folder
actor "One Drive Folder" as Kathy_View
actor "T3 Billing Inbox" as T3billing_Inbox
actor "Brandon's Inbox" as Brandon_Inbox
actor "Comcast Internet Portal" as Comcast_Internet_Portal
actor "New Relic Portal" as NewRelic_Portal
actor "Server Central Portal" as Deft_Portal
actor Addisu
actor Aleksei
actor Zef
actor Tony
actor Adobe_Acrobat_Pro_2020
actor Amex_Binder
actor Docusign


' Monthly Amex Statement Process

group Get Monthly Amex
Ana -> Brandon: Send Amex Workbook
end

group Amex Automation Process

    loop Until All Invoices Are Found
        group Initial Invoice Status
        Amex_Automation -> Amex: Check Amex Workbook
        note right of Amex_Automation: Highlight in Amex Workbook:\n Green for Present Invoices\nand Yellow for Missing Invoices in the Invoice_Folder
        Amex_Automation -> Invoice_Folder: Check Invoice Presence

        end

        group Attempt to Retrieve Missing Invoices

            group From T3 Billing Inbox
                Brandon -> T3billing_Inbox: Access Inbox
                T3billing_Inbox -> Brandon: Download Missing Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From Brandon's Inbox
                Brandon -> Brandon_Inbox: Access Account
                Brandon_Inbox -> Brandon: Download Missing Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From Aleksei
                Brandon -> Aleksei: Request Missing Invoices
                Aleksei -> Brandon: Provide Missing Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From Zef
                Brandon -> Zef: Request Missing Invoices
                Zef -> Brandon: Provide Missing Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From Addisu
                Brandon -> Addisu: Share Amex Workbook\nand Request Missing Invoices
                Addisu -> Brandon: Provide Missing Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From Comcast Internet Portal
                Brandon -> Comcast_Internet_Portal: Access Account
                Comcast_Internet_Portal -> Invoice_Folder: Download Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From New Relic Portal
                Brandon -> NewRelic_Portal: Access Account
                NewRelic_Portal -> Invoice_Folder: Download Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From Server Central Portal
                Brandon -> Deft_Portal: Access Account
                Deft_Portal -> Invoice_Folder: Download Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

        end

end

group Create PDF using Adobe Acrobat Pro
Amex_Automation -> Adobe_Acrobat_Pro_2020 : Utilizes for Creating Amex_Binders PDF; Amex_Binder_UNSIGNED_NOT_COMBINED and Amex_Binder_UNSIGNED_COMBINED
note right: Make Sure Page Width is 1 for Easier Reading
Amex_Binder -> Invoice_Folder: Save an Amex_Binder_UNSIGNED_COMBINED and Amex_Binder_UNSIGNED_NOT_COMBINED
end

end

group Get Signatures
Amex_Binder -> Docusign: Create Docusign
note left: Send Docusign of Amex_Binder PDF To be Signed by Addisu and Tony
Docusign -> Addisu: Get Signature for Amex_Binder
Docusign -> Tony: Get Signature for Amex_Binder
end

group Send Monthly Signed * Completed Amex_Binder PDF
Docusign -> Amex_Binder: Download Signed Amex_Binder_SIGNED
Amex_Binder -> Invoice_Folder: Save Signed Amex_Binder to Invoice_Folder
Brandon -> Ana: Send Copy of Signed Amex_Binder
end

@enduml
