@startuml

collections "Amex Workbook\n(Mar '24)" as Amex_Workbook
actor Ana
actor Brandon
control "Automation.py" as Amex_Automation
database "Invoice Folder" as Invoice_Folder
collections "One Drive Folder" as Kathy_View
collections "T3 Billing Inbox" as T3billing_Inbox
collections "Brandon's Inbox" as Brandon_Inbox
collections "Comcast Internet Portal" as Comcast_Internet_Portal
collections "New Relic Portal" as NewRelic_Portal
collections "Server Central Portal" as Deft_Portal
collections "CDW Portal" as CDW_Portal
actor Addisu
actor Aleksei
actor Zef
actor Kathy
control Adobe_Acrobat_Pro_2020
collections Amex_Binder
control Docusign
actor Kathy


' Monthly Amex Statement Process

group Get Monthly Amex_Workbook
Ana -> Brandon: Send Amex_Workbook
end

group Amex_Workbook Automation Process

    loop Attempt to Retrieve all Invoices Until All Invoices Are Found

        group Match Transactions and Invoices
        Amex_Automation -> Amex_Workbook: Check Amex_Workbook of All Transactions Recorded
        Amex_Automation -> Invoice_Folder: Process Automation; Extract Invoice PDF Data
        Amex_Automation -> Amex_Workbook: Process Automation; Match Invoice and Transaction and Highlight Amex_Workbook Yellow and Green

        end

            group From T3 Billing Inbox
                Brandon -> T3billing_Inbox: Access Inbox
                T3billing_Inbox -> Brandon: Download Missing Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From Brandon's Inbox
                Brandon -> Brandon_Inbox: Access Account
                Brandon_Inbox -> Brandon: Download Missing Invoices
                Brandon -> Invoice_Folder: Add the Invoices
            end

            group From Aleksei
                Brandon -> Aleksei: Request Missing Invoices
                Aleksei -> Brandon: Provide Missing Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From Zef
                Brandon -> Zef: Request Missing Invoices
                Zef -> Brandon: Provide Missing Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From Addisu
                Brandon -> Addisu: Share Amex_Workbook and Request Missing Invoices
                Addisu -> Brandon: Provide Missing Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From Comcast Internet Portal
                Brandon -> Comcast_Internet_Portal: Access Account
                Comcast_Internet_Portal -> Invoice_Folder: Download Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From New Relic Portal
                Brandon -> NewRelic_Portal: Access Account
                NewRelic_Portal -> Invoice_Folder: Download Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From Server Central Portal
                Brandon -> Deft_Portal: Access Account
                Deft_Portal -> Invoice_Folder: Download Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

            group From CDW Portal
                Brandon -> CDW_Portal: Access Account
                CDW_Portal -> Invoice_Folder: Download Invoices
                Brandon -> Invoice_Folder: Add Invoices
            end

end

group All Invoices in Invoice_Folder
Amex_Automation -> Invoice_Folder: Process Automation; Extract Invoice PDF Data
Amex_Automation -> Amex_Workbook: Process Automation; Updated Amex_Workbook with all Matching Invoices and Transactions
end

end

group Manual Process

    group Create PDF using Adobe Acrobat Pro
    Amex_Workbook -> Adobe_Acrobat_Pro_2020 : Upload Amex_Workbook
    note right: Make Sure Page Width is 1 for Easier Reading
    Invoice_Folder -> Adobe_Acrobat_Pro_2020: Upload Invoices
    Adobe_Acrobat_Pro_2020 -> Amex_Binder: Combine Amex_Workbook and Invoices PDF
    Amex_Binder -> Invoice_Folder: Save unsigned Amex_Binder to the Invoice_Folder
    end

    group Get Signatures
    Amex_Binder -> Docusign: Create Docusign: Send Docusign of Amex_Binder PDF To be Signed by Addisu and Kathy
    Docusign -> Addisu: Get Signature for Amex_Binder from Addisu; Addissu Signs Amex_Binder
    Docusign -> Kathy: Get Signature for Amex_Binder from Kathy; Kathy Signs Amex Binder
    end

    group Send Monthly Signed * Completed Amex_Binder PDF
    Docusign -> Amex_Binder: Download Signed Amex_Binder_SIGNED
    Amex_Binder -> Invoice_Folder: Save Signed Amex_Binder to Invoice_Folder
    Invoice_Folder -> Brandon: Make copy of Amex_Binder_SIGNED
    Brandon -> Ana: Send Copy of the Signed Amex_Binder
    end

end
@enduml
